// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Dur88_-x66ckr2QAinl9BrnwOnLW8mM',
    appId: '1:868775333555:web:68175286af5009c4462ac6',
    messagingSenderId: '868775333555',
    projectId: 'guide-touristique-matam',
    authDomain: 'guide-touristique-matam.firebaseapp.com',
    storageBucket: 'guide-touristique-matam.firebasestorage.app',
    measurementId: 'G-285Q8TR6XD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDriFSKkbfLvJjJn1yAOGbqmAeoqqKldI4',
    appId: '1:868775333555:android:33ff41b8dd772d49462ac6',
    messagingSenderId: '868775333555',
    projectId: 'guide-touristique-matam',
    storageBucket: 'guide-touristique-matam.firebasestorage.app',
  );
}
